services:
  - type: web
    name: kotha-hobe-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: kotha_hobe_super_secret_jwt_key_2026_production
      - key: MONGODB_URI
        value: mongodb://jiaulasif:iI0OqchzHmf3kDVV@ac-uph9exc-shard-00-00.jrphc7a.mongodb.net:27017,ac-uph9exc-shard-00-01.jrphc7a.mongodb.net:27017,ac-uph9exc-shard-00-02.jrphc7a.mongodb.net:27017/kotha_hobe?ssl=true&replicaSet=atlas-l80cpa-shard-0&authSource=admin&appName=SignUpInfo
      - key: FIREBASE_PROJECT_ID
        value: kothahobe-315c6
      - key: RESEND_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
